apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-hw3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: container-hw3
          image: gopalchada10010/swe645:01
          ports:
            - containerPort: 8080

